Repository camptocamp/docker-mapserver, pull requests merged in 2021-05, with the labels that each got.

#144 Fix typo in MS_MAP_PATTERN regexp
  Dockerfile
Labels: backport 7.0, backport 7.2, backport 7.4, backport 7.6

#152 Add the missing escapes
  Dockerfile
Labels: backport 7.4, backport master

#154 Add the missing escapes
  Dockerfile
Labels: backport 7.4

#159 Test MapServer with MAP
  acceptance_tests/conftest.py
  acceptance_tests/docker-compose.yaml
Labels: backport 7.0, backport 7.2, backport 7.4, backport 7.6

#164 Add missing file
  acceptance_tests/test_map.py
Labels: backport 7.0, backport 7.2, backport 7.4, backport 7.6
