Repository camptocamp/docker-mapserver, pull requests merged in 2022-11, with the labels that each got.

#355 Fix repository in workflow used to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#358 Create or update a Poetry group for Renovate
  .github/renovate.json5
  acceptance_tests/requirements.txt
Labels: chore

#359 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#360 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#361 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#362 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#363 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#364 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#365 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#366 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#367 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#368 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#369 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#371 Build the Arm image
  .github/workflows/main.yaml
  .github/workflows/rebuild.yaml
  Makefile
  ci/config.yaml
Labels: backport 8.0

#377 Replace deprecated --dev with --with=dev
  acceptance_tests/Dockerfile
Labels: chore

#378 Remove set local environment variables
  Dockerfile
Labels: chore

#386 Upgrade c2cciutils to a supported version
  .editorconfig
  .prettierignore
  README.md
  builder/build.sh
  builder/entry.sh
  checkout_release.sh
  ci/requirements.txt
  server/runtime/docker-entrypoint
  server/runtime/usr/local/bin/start-server
Labels: backport 7.4, backport 7.6

#389 Upgrade deprecated set-output commands
  .github/workflows/changelog.yaml
Labels: chore

#387 Permit access to api templates
  runtime/etc/apache2/conf-enabled/mapserver.conf
Labels: bug, backport 8.0

#401 End of support of version 7.0
  .github/renovate.json5
  .github/workflows/audit.yaml
  .github/workflows/main.yaml
  .github/workflows/rebuild.yaml
  SECURITY.md
Labels: chore
